-- Run this SQL query in your Supabase SQL Editor to create the table for storing placement records

create table if not exists public.placement_records (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    company_name text,
    company_mail text,
    company_address text,
    hr_name text,
    hr_mail text,
    placed_student_name text,
    department text,
    internship_or_placed text default 'Placed',
    stipend_salary text,
    package_lpa text,
    student_id text,
    student_mail_id text,
    student_address text,
    placed_year text,
    placed_sem text,
    date_of_join text,
    reference text,
    updated_at timestamp with time zone
);

-- Enable Row Level Security
alter table public.placement_records enable row level security;

-- Create Policies (Adjust these based on your strict security requirements)

-- Allow all authenticated users (Placement Officers, Coordinators) to read
create policy "Enable read access for all authenticated users"
on public.placement_records for select
to authenticated
using (true);

-- Allow authenticated users to insert
create policy "Enable insert for authenticated users"
on public.placement_records for insert
to authenticated
with check (true);

-- Allow authenticated users to update
create policy "Enable update for authenticated users"
on public.placement_records for update
to authenticated
using (true);

-- Allow authenticated users to delete
create policy "Enable delete for authenticated users"
on public.placement_records for delete
to authenticated
using (true);
